## **Naive Bayes**

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('play_tennis_dataset.csv')

In [3]:
data.head()

  Day   Outlook Temperature Humidity    Wind Play
0  D1  Overcast        Mild   Normal  Strong  Yes
1  D2     Sunny        Mild   Normal  Strong  Yes
2  D3       NaN        Mild     High  Strong   No
3  D4     Sunny        Mild     High    Weak  Yes
4  D5     Sunny        Cool   Normal  Strong  Yes

In [10]:
data.isna().mean()*100

Day            0.000000
Outlook        5.985599
Temperature    4.995500
Humidity       3.495350
Wind           5.490549
Play           0.000000
dtype: float64

In [5]:
data.shape

(6666, 6)

In [12]:
# drop nan values
data.dropna(inplace=True)

In [13]:
data.isna().sum()

Day            0
Outlook        0
Temperature    0
Humidity       0
Wind           0
Play           0
dtype: int64

In [14]:
data.shape

(5425, 6)

In [16]:
data.drop(columns=['Day'],inplace=True)

In [17]:
data.head()

    Outlook Temperature Humidity    Wind Play
0  Overcast        Mild   Normal  Strong  Yes
1     Sunny        Mild   Normal  Strong  Yes
3     Sunny        Mild     High    Weak  Yes
4     Sunny        Cool   Normal  Strong  Yes
6     Sunny        Mild     High    Weak  Yes

In [ ]:
from sklearn.naive_bayes import